# Generated by Django 2.2.1 on 2019-05-20 00:30

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.usuarios.models.UserManager()),
            ],
        ),
    ]
