# Generated by Django 2.2.1 on 2019-06-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.CharField(default='KQZ123', max_length=6),
        ),
    ]
