# Generated by Django 2.2.1 on 2019-06-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.CharField(default='KQZ123', max_length=7),
        ),
    ]
