# Generated by Django 2.2.1 on 2019-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190616_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.CharField(db_index=True, default='KQZ123', max_length=7, unique=True),
        ),
    ]
