# Generated by Django 2.2.1 on 2019-06-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20190616_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.CharField(db_index=True, max_length=7, unique=True),
        ),
    ]
