# Generated by Django 2.2.1 on 2019-05-26 05:13

import apps.inmuebles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_imagen', models.ImageField(upload_to=apps.inmuebles.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('predio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.CharField(max_length=180)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.TipoInmueble')),
            ],
        ),
    ]
