# Generated by Django 2.2.1 on 2019-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_auto_20190614_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='predio',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
