# Generated by Django 2.2.1 on 2019-05-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_auto_20190526_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='path_imagen',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebleImagenes', to='inmuebles.Inmueble'),
        ),
    ]
